import {
    PROD_FIREBASE_API_KEY,
    PROD_STRIPE_API_KEY,
    PROD_HEROKU_API_URL,
    PROD_URL_SCHEME,
    PROD_APPLE_MERCHANT_ID,

    DEV_FIREBASE_API_KEY,
    DEV_STRIPE_API_KEY,
    DEV_HEROKU_API_URL,
    DEV_URL_SCHEME,
    DEV_APPLE_MERCHANT_ID,
    
} from "@env"

const FIREBASE_API_KEY = PROD_FIREBASE_API_KEY
const STRIPE_API_KEY = DEV_STRIPE_API_KEY
const HEROKU_API_URL = PROD_HEROKU_API_URL
const URL_SCHEME = DEV_URL_SCHEME
const APPLE_MERCHANT_ID = DEV_APPLE_MERCHANT_ID

export {
    FIREBASE_API_KEY,
    STRIPE_API_KEY,
    HEROKU_API_URL,
    URL_SCHEME,
    APPLE_MERCHANT_ID
}